### ISSUE TITLE
I got an error.

### ISSUE THREAD

**Issue by HeinKoZin** [NavpreetDevpuri/LyndaDownloader#4]
**I got an error like this** :

Exercise File: exFile 11._Ethical_Hacking_Evading_IDS,_Firewalls,_and_Honeypots_(1h_52m)   [0.34Mb]
11. Ethical Hacking Evading IDS, Firewalls, and Honeypots (1h 52m)
 Total Videos : 31
    [360p:156.91Mb, 540p:203.27Mb, 720p:329.39Mb]
 
    [360p:156.91Mb, 540p:203.27Mb, 720p:329.39Mb]
Traceback (most recent call last):
  File "/content/LyndaDownloader/LyndaDownloaderLearningPaths.py", line 414, in <module>
    download()
  File "/content/LyndaDownloader/LyndaDownloaderLearningPaths.py", line 97, in download
    downloadedsize = int(temp[1])
ValueError: invalid literal for int() with base 10: ' Firewalls'

**Comment by NavpreetDevpuri** [comment]
show me the value of `temp[1]` 
just add a line `print(temp[1])` just before that line 97

**Comment by NavpreetDevpuri** [comment]
ur `temp.txt` file somehow changed to wrong values. 
u should try to download it again.
u can skip videos by changing, I think `textt.txt` file

**Comment by HeinKoZin** [comment]
Thanks, bro. It worked fine.
