### ISSUE TITLE
Issue while downloading a learning path -ValueError: invalid literal for int() with base 10: ' Queues'

### ISSUE THREAD

**Issue by sim44m** [NavpreetDevpuri/LyndaDownloader#6]
im getting below error while downloading this learning path - [https://www.lynda.com/learning-paths/Developer/advance-your-skills-in-python](url)

Please help.
the first 3 courses downloaded successfully but this one gets stuck always.

```
4. Python Data Structures  Stacks, Queues, and Deques (1h 24m)
 Total Videos : 33
    [360p:107.58Mb, 540p:147.7Mb, 720p:203.34Mb]
 
    [360p:107.58Mb, 540p:147.7Mb, 720p:203.34Mb]
Enter video quality (0 for 360p, 1 for 540p or 2 for 720p) : 2
Traceback (most recent call last):
  File "/content/LyndaDownloader/LyndaDownloaderLearningPaths.py", line 414, in <module>
    download()
  File "/content/LyndaDownloader/LyndaDownloaderLearningPaths.py", line 97, in download
    downloadedsize = int(temp[1])
ValueError: invalid literal for int() with base 10: ' Queues'
```

**Comment by NavpreetDevpuri** [comment]
Almost understood the problem, it is due to having coma (,) in course title. I will resolve it as soon as possible.

**Comment by sim44m** [comment]
Thank you.

**Comment by NavpreetDevpuri** [comment]
Try to replace `validname()` at line 67 to following 
```python
def validname(name):
    return name.replace('|', '').replace('>', '').replace('<', '').replace('"', '').replace('?', '').replace('*',
                                                                                                             '').replace(
        ':', '').replace('/', '').replace('\\', '').replace("\r", "").replace("\n", "").replace("\t", "").replace(",","")

```

**Comment by sim44m** [comment]
yeah it worked, thanks.
