### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Th3-A6add0n** [NavpreetDevpuri/LyndaDownloader#8]
Traceback (most recent call last):
  File "/Drive/drive/_lynda_course_downloader/LyndaDownloader/LyndaDownloader.py", line 191, in getVideosLinks
    videodata[1]['urls']['720']
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Drive/drive/_lynda_course_downloader/LyndaDownloader/LyndaDownloader.py", line 194, in getVideosLinks
    videodata[1]['urls']['540']
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Drive/drive/_lynda_course_downloader/LyndaDownloader/LyndaDownloader.py", line 322, in <module>
    getVideosLinks()
  File "/Drive/drive/_lynda_course_downloader/LyndaDownloader/LyndaDownloader.py", line 197, in getVideosLinks
    [videodata[1]['urls']['360']])
IndexError: list index out of range

**Comment by NavpreetDevpuri** [comment]
This seems like a network error. Try again. You can add full [output](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks)

**Comment by ogeeDeveloper** [comment]
I am also having this issue as well.  It happens when its gathering the course videos.
![image](https://user-images.githubusercontent.com/74021270/105733793-ec5b2600-5eff-11eb-8ad0-a53372059de9.png)

**Comment by NavpreetDevpuri** [comment]
does it always show an error on the exact same video file?

**Comment by ogeeDeveloper** [comment]
> does it always show an error on the exact same video file?

This is a different course i am trying to download and its coming with this error

**Comment by NavpreetDevpuri** [comment]
just started a new project [linkedin-learning-downloader](https://github.com/NavpreetDevpuri/linkedin-learning-downloader) that will have more clean code and will not have that bug.
